#################################################################
## Location Automations
#################################################################

        ##########################################################
        ## Set userone Away after 2 Min
        ##########################################################

- alias: location set userone away after 2 mins
  trigger:
    - platform: state
      entity_id: device_tracker.useronedevice
      from: 'home'
      to: 'not_home'
      for:
        hours: 0
        minutes: 2
        seconds: 0
  action:
    - service: homeassistant.turn_on
      entity_id:
        - input_boolean.userone_greeting
        - input_boolean.userone_away

        ##########################################################
        ## Set usertwo Away after 2 Min
        ##########################################################

- alias: location set usertwo away after 2 mins
  trigger:
    - platform: state
      entity_id: device_tracker.usertwodevice
      from: 'home'
      to: 'not_home'
      for:
        hours: 0
        minutes: 2
        seconds: 0
  action:
    - service: homeassistant.turn_on
      entity_id:
        - input_boolean.usertwo_greeting
        - input_boolean.usertwo_away

        ##########################################################
        ## Set Garage Notification On If No One Home
        ##########################################################

- alias: location set garage notification on if no one home
  trigger:
    - platform: state
      entity_id: group.household
      to: 'not_home'
      for:
        hours: 0
        minutes: 2
        seconds: 0
  condition:
    condition: or
    conditions:
      - condition: numeric_state
        entity_id: sensor.usertwo_to_home
        above: 10
      - condition: numeric_state
        entity_id: sensor.userone_to_home
        above: 10
  action:
    - service: homeassistant.turn_on
      entity_id:
        - input_boolean.garage_notification

        ##########################################################
        ## Set Garage Notification Off If Close To Home
        ##########################################################

- alias: location set garage notication off if close to home
  trigger:
    - platform: numeric_state
      entity_id: sensor.usertwo_to_home
      below: 9
      above: 0
    - platform: numeric_state
      entity_id: sensor.userone_to_home
      below: 9
      above: 0
    - platform: state
      entity_id: device_tracker.useronedevice
      to: 'home'
    - platform: state
      entity_id: device_tracker.usertwodevice
      to: 'home'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.garage_notification

        ##########################################################
        ## Set userone Home after 5 Mins
        ##########################################################

- alias: location set userone home after 5 mins
  trigger:
    - platform: state
      entity_id: device_tracker.useronedevice
      to: 'home'
      for:
        hours: 0
        minutes: 5
        seconds: 0
  action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.userone_away
        - input_boolean.userone_away_driving
        - input_boolean.userone_greeting

        ##########################################################
        ## Set usertwo Home after 5 Mins
        ##########################################################

- alias: location set usertwo home after 5 mins
  trigger:
    - platform: state
      entity_id: device_tracker.usertwodevice
      to: 'home'
      for:
        hours: 0
        minutes: 5
        seconds: 0
  action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.usertwo_away
        - input_boolean.usertwo_away_driving

        ##########################################################
        ## Set userone Away Driving
        ##########################################################

- alias: location set userone away driving
  trigger:
    - platform: state
      entity_id: device_tracker.useronedevice
      from: 'home'
      to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.garage_occupancy
      state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.userone_away_driving

        ##########################################################
        ## Set usertwo Away Driving
        ##########################################################

- alias: location set usertwo away driving
  trigger:
    - platform: state
      entity_id: device_tracker.usertwodevice
      from: 'home'
      to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.garage_occupancy
      state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.usertwo_away_driving

        ##########################################################
        ## Manually Set userone Away
        ##########################################################

- alias: location manually set userone away
  trigger:
    - platform: state
      entity_id: input_boolean.manual_userone_away
      from: 'off'
      to: 'on'
  action:
    - service: device_tracker.see
      data:
        dev_id: useronedevice
        location_name: 'not_home'

        ##########################################################
        ## Reset Manually Set userone Away Switch
        ##########################################################

- alias: location reset manually set userone away
  trigger:
    - platform: state
      entity_id: input_boolean.manual_userone_away
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 30
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.manual_userone_away

        ##########################################################
        ## Manually Set usertwo Away
        ##########################################################

- alias: location manually set usertwo away
  trigger:
    - platform: state
      entity_id: input_boolean.manual_usertwo_away
      from: 'off'
      to: 'on'
  action:
    - service: device_tracker.see
      data:
        dev_id: usertwodevice
        location_name: 'not_home'

        ##########################################################
        ## Reset Manually Set usertwo Away Switch
        ##########################################################

- alias: location reset manually set usertwo away
  trigger:
    - platform: state
      entity_id: input_boolean.manual_usertwo_away
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 30
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.manual_usertwo_away

        ##########################################################
        ## Manually Set userone Home
        ##########################################################

- alias: location manually set userone home
  trigger:
    - platform: state
      entity_id: input_boolean.manual_userone_home
      from: 'off'
      to: 'on'
  action:
    - service: device_tracker.see
      data:
        dev_id: useronedevice
        location_name: 'home'

        ##########################################################
        ## Reset Manually Set userone Home Switch
        ##########################################################

- alias: location reset userone home
  trigger:
    - platform: state
      entity_id: input_boolean.manual_userone_home
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 30
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.manual_userone_home

        ##########################################################
        ## Manually Set usertwo Home
        ##########################################################

- alias: location manually set usertwo home
  trigger:
    - platform: state
      entity_id: input_boolean.manual_usertwo_home
      from: 'off'
      to: 'on'
  action:
    - service: device_tracker.see
      data:
        dev_id: usertwodevice
        location_name: 'home'

        ##########################################################
        ## Reset Manually Set usertwo Home Switch
        ##########################################################

- alias: location reset usertwo home
  trigger:
    - platform: state
      entity_id: input_boolean.manual_usertwo_home
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 30
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.manual_usertwo_home

- alias: Location - Request Location Update iOS
  trigger:
    platform: time
    minutes: '/30'
    seconds: 00
  action:
    - service: notify.ios_green_ipad
      data:
       message: "request_location_update"
    - service: notify.ios_pink_ipad
      data:
       message: "request_location_update"
    - service: notify.ios_userones_iphone
      data:
       message: "request_location_update"
